In [1]:
import numpy as np

In [12]:
# creating array from list


arr = np.array([1,2,3,4,5])
print(arr , type(arr) , arr.dtype , arr.shape)


arr2 = np.array([1,2,3,4,5,"vaishnavi"])
print(arr , type(arr), arr2.dtype , arr2.shape) #U21 = unicode





arr2d = np.array([[1,2,3],[4,5,6],[7,8,9] ,[10,11,12]])
print(arr2d , arr2d.shape) #shape(dimension) = row x column 

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
[1 2 3 4 5] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [29]:
#creating arrays from scratch

arr1= np.zeros((2,3),dtype="int64") #dimensions  #prefill with zero valeus
print(arr1 , arr1.shape)


arr4= np.ones((2,3),dtype="int64")
print(arr4 , arr4.shape)


arr6= np.full((2,3),100) #fill all with 100
print(arr6 , arr6.shape)


arr5= np.eye(3) #eye = identity matrix
print(arr5 , arr5.shape)


arr7= np.arange(1,10,2) #just like python range(start , stop , step)
print(arr7)


arr8= np.linspace(1,100,3) #evenly spaced arrays(start , stop , arraysize)
print(arr8)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9]
[  1.   50.5 100. ]


In [36]:
#properties of numpy array

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #for dimensions

print(arr.size) #total elements

print(arr.dtype) #datatype

print(arr.ndim) #n-dimensional array

#type casting

float_arr = arr.astype(np.float64)
print(float_arr , float_arr.dtype)





(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [39]:
#operations on arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped , reshaped.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened , flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [44]:
#Indexing

#arr = np.array([1,2,3,4,5])


#print(arr[0])
#print(arr[3])

arr = np.array([[1,2,3],[4,5,6],[4,5,8]])
print(arr)

print(arr[1][2])

print(arr[2][1])

[[1 2 3]
 [4 5 6]
 [4 5 8]]
6
5


In [47]:
#fancy indexing

arr = np.array([1,2,3,4,5])

idx = [0,4,1]

print(arr[idx])

#Boolean indexing

print(arr[arr > 3])
print(arr[arr% 2])




[1 5 2]
[4 5]
[2 1 2 1 2]


In [55]:
#Slicing Operetion

arr = np.array([1,2,3,4,5])

print(arr[1:4]) #[start,stop,step]

print(arr[1:])

print(arr[:4])

print(arr[:])

print(arr[::1])



[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 2 3 4 5]


In [62]:
# COPY in python list 
        #VS
# VIEW in numpy array

#nums = [1,2,3,4,5]
#sub_list = nums[1:3]
#print(sub_list)

#sub_list[0] = 200 #changed value
#print(sub_list) #updated sublist
#print(nums) #gives original list

arr = np.array([1,2,3,4,5])
sub_arr =arr[1:3]
print(sub_arr)

sub_arr[0] = 200 #changed value
print(sub_arr) #updated sub-arr
print(arr) #updated original arry


[2 3]
[200   3]
[  1 200   3   4   5]


In [66]:
#data types


arr = np.array([1,2,3.1,4,5,6,"machine learning"])

print(arr , arr.dtype)


['1' '2' '3.1' '4' '5' '6' 'machine learning'] <U32


In [71]:
#complex num

arr1 = np.array([3 + 4j])
arr2 = np.array([2 + 1j])
print(arr1+ arr2)
print(arr1- arr2)

[5.+5.j]
[1.+3.j]


In [73]:
# Object type

arr = np.array(["ML" , {1,2,3} , 42])
print(arr , arr.dtype)

['ML' {1, 2, 3} 42] object


In [80]:
#Multi dimentional array
#AXES

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)


print(np.sum(arr2d))


#axes
#sum of column
sum_of_col = np.sum(arr2d , axis = 0)
print(sum_of_col)

#sum of row
sum_of_row = np.sum(arr2d , axis = 1)
print(sum_of_row)

print(arr2d[0:2 , 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [88]:
#3D array


arr = np.array([[[1,2],[3,4],[6,7]],[[1,3],[4,8],[1,9]]]) # 2x2x3
print(arr , arr.shape)



# indexng

print(arr[0,1,1])
print(arr[1,1,0])
print(arr[1,2,1])


#slicing
print(arr[:,0,:])


[[[1 2]
  [3 4]
  [6 7]]

 [[1 3]
  [4 8]
  [1 9]]] (2, 3, 2)
4
4
9
[[1 2]
 [1 3]]
