In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([2,5,4,3,2])
print(arr ** 2)
print(arr + 10)
print(arr + arr1)


[ 1  4  9 16 25]
[11 12 13 14 15]
[3 7 7 7 7]


In [4]:
#broadcasting


arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5] ,[4,5,6,3,2]])
print(arr + 5)
print(arr + arr2)
print(arr2,arr2.shape)


[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 5  7  9  7  7]]
[[1 2 3 4 5]
 [4 5 6 3 2]] (2, 5)


In [5]:
#normalisation

arr = np.array([[1,2] ,[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean)/std_dev
print(normalized_arr)


print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [23]:
# Mathematical functions

# Aggregation

arr = np.array([1,2,3,4,5,])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmax(arr)) #index of max value
print(np.argmin(arr)) # index of min value
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))



#Power 

print(np.square(arr))
print(np.sqrt(arr))


#Log Function
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))



15
120
1
5
4
0
3.0
1.4142135623730951
3.0
2.0
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [27]:
#rounding 


print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [33]:
arr = np.array([1,2,3,5,-6,4,2,4,5,])

print(np.unique(arr))
print(np.sort(arr))


print(np.abs(arr))  #makes all values positive and return

[-6  1  2  3  4  5]
[-6  1  2  2  3  4  4  5  5]
[1 2 3 5 6 4 2 4 5]
